In [1]:
import numpy as np

Basic Commands

In [2]:
print('fit a model with', 11, 'variables')


fit a model with 11 variables


In [3]:
print?


In [4]:
3+5


8

In [5]:
"hello" + " " + "world"


'hello world'

In [6]:
x = [3, 4, 5]
x

[3, 4, 5]

In [7]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

Introduction to Numerical Python

In [8]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [9]:
x+y

array([ 7, 13, 12])

In [10]:
x = np.random.normal(size = 50)
x

array([-0.94509381, -0.73838037, -0.09186779,  0.51991037, -0.20948794,
        1.80760601, -0.21597593, -0.84130278, -0.54756556, -0.93641589,
       -0.47631684, -0.14079761,  0.93698316,  0.06706111, -1.15939354,
       -1.39570774,  1.5116327 ,  0.02148818,  0.81549209,  0.26869674,
       -0.74825752,  1.05610144, -0.78436207,  0.30581157,  1.47381398,
       -0.07555814, -0.4602696 ,  0.87882009,  1.03001284,  0.68176418,
       -0.12997384, -0.4466858 ,  1.74227652, -0.34489725,  0.37469011,
       -0.41082491,  1.37410632,  0.70966635, -0.38021668, -0.4970576 ,
       -0.02553378,  0.22138245, -0.85188153, -0.69649615,  0.04756157,
        1.00984673, -0.79572256,  0.67363989,  1.28240458, -1.11095797])

In [11]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
x.ndim

2

In [13]:
x.dtype

dtype('int32')

In [14]:
np.array([[1, 2], [3.0, 4]]).dtype


dtype('float64')

In [15]:
np.array?


In [16]:
np.array([[1, 2], [3, 4]], float).dtype


dtype('float64')

In [17]:
x.shape


(2, 2)

In [18]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [19]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [20]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [21]:
x_reshape[0, 0] 

1

In [22]:
x_reshape[1, 2] 

6

In [23]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [24]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T


In [ ]:
np.sqrt(x)


In [ ]:
x**2


In [ ]:
x**0.5


In [ ]:
x = np.random.normal(size=50)
x

In [ ]:
y = x + np.random.normal(loc=50, scale = 1, size = 50)
y

In [ ]:
np.corrcoef(x, y)

In [ ]:
print(np.random.normal(scale = 5, size = 2))

In [ ]:
rng = np.random.default_rng(1234)
print(rng.normal())
rng2 = np.random.default_rng(1234)
print(rng2.normal())

In [ ]:
rng = np.random.default_rng(4)
y = rng.standard_normal(10)
y.mean(), np.mean(y)

In [ ]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

In [ ]:
np.sqrt(np.var(y)), np.std(y)

In [ ]:
x = rng.standard_normal((10,3))
x

In [ ]:
x.mean(axis=1)

In [ ]:
x.mean(0)

Graphics

In [ ]:
from matplotlib.pyplot import subplots
fig, ax = subplots(figsize=(8,8))
x = rng.standard_normal(100)
y = rng.standard_normal(100)
ax.plot(x,y)

# fig, ax = subplots(figsize=(8, 8))
# x = rng.standard_normal(100)
# y = rng.standard_normal(100)
# ax.plot(x, y);

In [ ]:
# output = subplots(figsize=(8, 8))
# fig = output[0]
# ax = output[1]

output = subplots(figsize=(8,8))
fig = output[0]
ax = output[1]

In [ ]:
fig, ax = subplots(figsize=(8,8))
ax.plot(x,y,'o')

In [ ]:
fig, ax = subplots(figsize=(8,8))
ax.scatter(x,y,marker='x');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.scatter(x, y, marker='o')

In [ ]:
fig, ax = subplots(figsize=(8,8))
ax.scatter(x,y,marker='o')
ax.set_xlabel("this is the x-axis")
ax.set_ylabel("this is the y-axis")
ax.set_title("Plot of X vs Y");

In [ ]:
fig.set_size_inches(12,3)
fig

In [ ]:
fig, axes = subplots(nrows=2,
                     ncols=3,
                     figsize=(15, 5))

In [ ]:
axes[0,1].plot(x, y, 'o')
axes[1,2].scatter(x, y, marker='+')
fig

In [ ]:
fig.savefig("Figure.png", dpi=400)
fig.savefig("Figure.pdf", dpi=200);

In [ ]:
axes[0,1].set_xlim([-1,1])
fig.savefig("Figure_updated.jpg")
fig

In [ ]:
# fig, ax = subplots(figsize=(8, 8))
# x = np.linspace(-np.pi, np.pi, 50)
# y = x
# f = np.multiply.outer(np.cos(y), 1 / (1 + x**2))
# ax.contour(x, y, f);

fig, ax = subplots(figsize=(8,8))
x = np.linspace(-np.pi, np.pi, 50)
y = x
f = np.multiply.outer(np.cos(y), 1/ (1 + x**2))
ax.contour(x,y,f);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.contour(x, y, f, levels=45);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.imshow(f);

**Sequences and Slice Notation**

In [ ]:
seq1 = np.linspace(0, 10, 11)
seq1

In [ ]:
seq2 = np.arange(0, 10)
seq2

In [ ]:
"hello world"[3:6]

In [ ]:
"hello world"[slice(3,6)]

**Indexing Data**

In [ ]:
A = np.array(np.arange(16)).reshape((4, 4))
A

In [ ]:
A[1,2]

In [ ]:
A[[1,3]]

In [ ]:
A[:,[0,2]]


In [ ]:
A[[1,3],[0,2]]


In [ ]:
np.array([A[1,0],A[3,2]])

In [ ]:
A[[1,3],[0,2,3]]


In [ ]:
A[[1,3]][:,[0,2]]


In [ ]:
idx = np.ix_([1,3],[0,2,3])
A[idx]


In [ ]:
A[1:4:2,0:3:2]


**Boolean Indexing**

In [ ]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

In [ ]:
keep_rows[[1,3]] = True
keep_rows

In [ ]:
np.all(keep_rows == np.array([0,1,0,1]))


In [ ]:
A[np.array([0,1,0,1])]

In [ ]:
A[keep_rows]


In [ ]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]

In [ ]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]

**Loading Data**

In [ ]:
import pandas as pd
Auto = pd.read_csv('Auto.csv')
Auto

In [ ]:
Auto = pd.read_csv('Auto.data', delim_whitespace=True)


In [ ]:
Auto['horsepower']

In [ ]:
np.unique(Auto['horsepower'])


In [ ]:
Auto = pd.read_csv('Auto.data',
                   na_values=['?'],
                   delim_whitespace=True)
Auto['horsepower'].sum()


In [ ]:
Auto.shape


In [ ]:
Auto_new = Auto.dropna()
Auto_new.shape

Basics of Selecting Rows and Colums

In [ ]:
Auto = Auto_new # overwrite the previous value
Auto.columns

In [ ]:
Auto[:3]

In [ ]:
idx_80 = Auto['year'] > 80
Auto[idx_80]


In [ ]:
Auto[['mpg', 'horsepower']]


In [ ]:
Auto.index


In [ ]:
Auto_re = Auto.set_index('name')
Auto_re

In [ ]:
Auto_re.columns

In [ ]:
rows = ['amc rebel sst', 'ford torino']
Auto_re.loc[rows]

In [ ]:
Auto_re.iloc[[3,4]]

In [ ]:
Auto_re.iloc[:,[0,2,3]]


In [ ]:
Auto_re.iloc[[3,4],[0,2,3]]


In [ ]:
Auto_re.loc['ford galaxie 500', ['mpg', 'origin']]


More on Selecting Rows and Columns

In [ ]:
idx_80 = Auto_re['year'] > 80
Auto_re.loc[idx_80, ['weight', 'origin']]

In [ ]:
Auto_re.loc[lambda df: df['year'] > 80, ['weight', 'origin']]

In [ ]:

Auto_re.loc[lambda df: (df['year'] > 80) & (df['mpg'] > 30), ['weight', 'origin']]

In [ ]:
Auto_re.loc[lambda df: (df['displacement'] < 300)
                       & (df.index.str.contains('ford')
                       | df.index.str.contains('datsun')),
            ['weight', 'origin']
           ]


**For Loops**

In [ ]:
total = 0
for value in [3,2,19]:
    total += value
print('Total is: {0}'.format(total))


In [ ]:
total = 0
for value in [2,3,19]:
    for weight in [3, 2, 1]:
        total += value * weight
print('Total is: {0}'.format(total))

In [ ]:
total = 0
for value, weight in zip([2,3,19],
                         [0.2,0.3,0.5]):
    total += weight * value
print('Weighted average is: {0}'.format(total))

**String Formatting**

In [ ]:
rng = np.random.default_rng(1)
A = rng.standard_normal((127, 5))
M = rng.choice([0, np.nan], p=[0.8,0.2], size=A.shape)
A += M
D = pd.DataFrame(A, columns=['food',
                             'bar',
                             'pickle',
                             'snack',
                             'popcorn'])
D[:9]

In [ ]:
for col in D.columns:
    template = 'Column "{0}" has {1:.2%} missing values'
    print(template.format(col,
          np.isnan(D[col]).mean()))

Additional Graphs and Numerical Summaries

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(horsepower, mpg, 'o');

In [ ]:
fig, ax = subplots(figsize=(8, 8))
ax.plot(Auto['horsepower'], Auto['mpg'], 'o');


In [ ]:
ax = Auto.plot.scatter('horsepower', 'mpg')
ax.set_title('Horsepower vs. MPG');

In [ ]:
fig = ax.figure
fig.savefig('horsepower_mpg.png');

In [ ]:

fig, axes = subplots(ncols=3, figsize=(15, 5))
Auto.plot.scatter('horsepower', 'mpg', ax=axes[1]);

In [ ]:
Auto.cylinders = pd.Series(Auto.cylinders, dtype='category')
Auto.cylinders.dtype

In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.boxplot('mpg', by='cylinders', ax=ax);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.hist('mpg', ax=ax);

In [ ]:
fig, ax = subplots(figsize=(8, 8))
Auto.hist('mpg', color='red', bins=12, ax=ax);


In [ ]:
pd.plotting.scatter_matrix(Auto);


In [ ]:
pd.plotting.scatter_matrix(Auto[['mpg',
                                 'displacement',
                                 'weight']]);

In [ ]:
Auto['mpg'].describe()

In [ ]:
Auto['cylinders'].describe()
Auto['mpg'].describe()
